# Functions in python

## functions VS Methods: 
## A method refers to a function which is part of a class, where as the function 
## dosent have such restriction-  it just points to standalone function

In [1]:
def plus(*args):
  return sum(args)

# Calculate the sum
plus(1,4,5)

10

## Anonymous Function



In [5]:
# `sum()` lambda function
sum = lambda x, y: x + y;

# Call the `sum()` anonymous function
sum(4,5)

# "Translate" to a UDF
def sum(x, y):
    return x+y


#==================mostly used when we user -filter/reduce/map

from functools import reduce

my_list = [1,2,3,4,5,6,7,8,9,10]

# Use lambda function with `filter()`
filtered_list = list(filter(lambda x: (x*2 > 10), my_list))

# Use lambda function with `map()`
mapped_list = list(map(lambda x: x*2, my_list))

# Use lambda function with `reduce()`
reduced_list = reduce(lambda x, y: x+y, my_list)

print(filtered_list)
print(mapped_list)
print(reduced_list)

[6, 7, 8, 9, 10]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
55


In [7]:
# Define `main()` function
def hello():
    print('hello')
    
def main():
  hello()
  print("This is a main function")


# Execute `main()` function 
if __name__ == '__main__':
    main()

hello
This is a main function


In [10]:
# using Arbitrary Keyword Arguments, **kwargs

def my_func(**car):
    print("model of the car is "+car['model'])
my_func(model='honda city 2019',name='zonda',version='automatic')

model of the car is honda city 2019


In [11]:
#recursive Function
def factorial(x):
    """This is a recursive function
    to find the factorial of an integer"""

    if x == 1:
        return 1
    else:
        return (x * factorial(x-1))


num = 3
print("The factorial of", num, "is", factorial(num))

The factorial of 3 is 6


In [ ]:
#File Handling

# open() function
'''
"r" - Read - Default value. Opens a file for reading, error if the file does not exist

"a" - Append - Opens a file for appending, creates the file if it does not exist

"w" - Write - Opens a file for writing, creates the file if it does not exist

"x" - Create - Creates the specified file, returns an error if the file exists


and opening file is handled as 

"t" - Text - Default value. Text mode

"b" - Binary - Binary mode (e.g. images)

'''
# f = open("demofile.txt", "r") 
# f.read()

# os.remove("demofile.txt")  # Deleting a file

In [12]:
import os
if os.path.exists("demofile.txt"):
    os.remove("demofile.txt")
else:
    print("The file does not exist")



The file does not exist


In [ ]:
#unzip all the file in folders 

import zipfile
with zipfile.ZipFile(path_to_zip_file,'r') as zip_ref:
    zip_ref.extract_all(extract_to_some_location)
    

In [13]:
#iterators in python

mytuple = ("apple", "banana", "cherry")

myit = iter(mytuple)

print(next(myit))
print(next(myit))
print(next(myit))

apple
banana
cherry


In [ ]:
#exception handling
try:
    print(x)
except:
    print("Something went wrong")
finally:
    print("The 'try except' is finished")

## REGEX in py

In [ ]:
[]	A set of characters	"[a-m]"	
\	Signals a special sequence (can also be used to escape special characters)	"\d"	
.	Any character (except newline character)	"he..o"	
^	Starts with	"^hello"	
$	Ends with	"world$"	
*	Zero or more occurrences	"aix*"	
+	One or more occurrences	"aix+"	
{}	Exactly the specified number of occurrences	"al{2}"	
|	Either or	"falls|stays"

\A	Returns a match if the specified characters are at the beginning of the string	"\AThe"	
\b	Returns a match where the specified characters are at the beginning or at the end of a word
(the "r" in the beginning is making sure that the string is being treated as a "raw string")	r"\bain"
r"ain\b"	
\B	Returns a match where the specified characters are present, but NOT at the beginning (or at the end) of a word
(the "r" in the beginning is making sure that the string is being treated as a "raw string")	r"\Bain"
r"ain\B"	
\d	Returns a match where the string contains digits (numbers from 0-9)	"\d"	
\D	Returns a match where the string DOES NOT contain digits	"\D"	
\s	Returns a match where the string contains a white space character	"\s"	
\S	Returns a match where the string DOES NOT contain a white space character	"\S"	
\w	Returns a match where the string contains any word characters (characters from a to Z, digits from 0-9, and the underscore _ character)	"\w"	
\W	Returns a match where the string DOES NOT contain any word characters	"\W"	
\Z	Returns a match if the specified characters are at the end of the string	"Spain\Z"

# Numpy

In [28]:
#operations
import numpy as np
a= np.array([2,3,5,6]) # 1D Array
type(a)

# creating 0 Dimension array
a = np.array(22)
a

# creating 2D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

# 3-D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

a.ndim
arr.ndim # checking no. of Dimension


arr = np.array([1, 2, 3, 4], ndmin=5)
arr

arr = np.array([1, 2, 3, 4])

# print(arr[2] + arr[3])

# print(arr[:4])

# print(arr[::2])

arr.shape

[1 2 3 4]
[1 3]


(4,)

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# 1D to 2D
newarr = arr.reshape(4, 3)
newarr

# 1D to 3D
newarr3d = arr.reshape(2, 3, 2)
newarr3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

## Flattening array means converting a multidimensional array into a 1D array.

# We can use reshape(-1) to do this.

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
newarr



array([1, 2, 3, 4, 5, 6])

In [35]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [36]:
# Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
np.where(arr == 4)

[array([1, 2]), array([3, 4]), array([5, 6])]


(array([3], dtype=int64),)


# MATPLOTLIB

# PANDAS

In [ ]:
'''
its all abt dataframe
dataframe is in 2D format

while series is in 1D format

Series
A Series, by contrast, is a sequence of data values. 
If a DataFrame is a table, a Series is a list.
And in fact you can create one with nothing more than a list:




series is single column data frame


df=pd.read_csv(" ", index_col=0)

df=pd.read_excel()

df.shape

df.head()





'''

In [ ]:
# index based selection - let say df is dataframe has 5 cols and 100 rows
# df.iloc[rows,cols] or df.loc[rows,cols]
#df.iloc[0:20,['col1','col2','col3']]

#df.loc[:,['col1','col2']]

#here review is a dataframe, country and points are cols
#reviews.loc[reviews.country == 'Italy']
#reviews.country.unique()

#reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)]

#reviews.loc[reviews.price.notnull()]

#reviews.taster_name.value_counts()



#map() function

# review_points_mean = reviews.points.mean()
# reviews.points.map(lambda p: p - review_points_mean)



# apply() function
# def remean_points(row):
#     row.points = row.points - review_points_mean
#     return row

# reviews.apply(remean_points, axis='columns')

'''Note that map() and apply() return new, transformed Series and DataFrames, respectively. 
They don't modify the original data they're called on.
If we look at the first row of reviews, 
we can see that it still has its original points value.'''


In [ ]:
# renaming column of dataframe
reviews.rename(columns={'points': 'score'})


In [ ]:
canadian_youtube = pd.read_csv("../input/youtube-new/CAvideos.csv")
british_youtube = pd.read_csv("../input/youtube-new/GBvideos.csv")

pd.concat([canadian_youtube, british_youtube])

In [ ]:
reviews.price.dtype

'''It's possible to convert a column of one type into another 
wherever such a conversion makes sense by using the astype()
function. For example, we may transform the points column 
from its existing int64 data type into a float64 data type:
'''
reviews.points.astype('float64')

In [ ]:
#find null values
reviews[pd.isnull(reviews.country)]


#filling null/NaN values with some value
reviews.region_2.fillna("Unknown")

#replacing certain value in a column
reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

In [ ]:
Groupwise analysis
One function we've been using heavily thus far is the 
value_counts() function. We can replicate what 
value_counts() does by doing the following:

reviews.groupby('points').points.count()

reviews.groupby('points').price.min()

In [ ]:
You can think of each group we generate as being a slice
of our DataFrame containing only data with values that
match. This DataFrame is accessible to us directly using
the apply() method, and we can then manipulate the data 
in any way we see fit. For example, here's one way of 
selecting the name of the first wine reviewed from each
winery in the dataset:

reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

In [ ]:
countries_reviewed.sort_values(by='len')
#len is the column in dataframe
countries_reviewed.sort_values(by='len', ascending=False)

countries_reviewed.sort_values(by=['country', 'len'])
